### ISSUE TITLE
Fix for normal/c2p1x1_5_c5_030.s

### ISSUE THREAD

**Issue by pawelmat** [Kalmalyzer/kalms-c2p#2]
normal/c2p1x1_5_c5_030.s has an error in creating tempbuf for the last bitplane. Here's the fix:

Lines 169-172 should be removed:
	lsl.l	#6,d1			; Swap/Merge 2x4, part 1
	lsl.l	#4,d3
	or.l	d1,d3
	move.l	d3,a4

And replaced by:
	lsl.l	#2,d1			; Swap/Merge 2x4, part 1
	or.l	d1,d3
	move.l	d3,(a3)+
	
Line 195 should be removed:
	add.l	a4,d1

**Comment by Kalmalyzer** [comment]
Thanks for the heads up. Would you mind making a PR with the change too? I hear it gives Internet karma!

**Comment by pawelmat** [comment]
Done, PR#3

**Comment by Kalmalyzer** [comment]
Thanks for the fix!
